server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: MATH
          uri: lb://MATH/
          predicates:
            - Path=/MATH/**
        - id: HISTORY
          uri: lb://HISTORY/
          predicates:
            - Path=/HISTORY/**
      httpserver:
        wiretap: true
  discovery:
    locator:
      enabled: true
      lowerCaseServiceId: true
  main:
    web-application-type: reactive
reactor:
  netty: TRACE
