server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: MATH
          uri: http://localhost:8083/
          predicates:
            - Path=/MATH/**
        - id: HISTORY
          uri: http://localhost:8085/
          predicates:
            - Path=/HISTORY/**
  main:
    web-application-type: reactive