server:
  port: 8761

spring:
  application:
    name: discovery-service


eureka:
  client:
   register-with-eureka: false
   fetch-registry: false
   service-url:
    defaultZone: http://localhost:${server.port:8761}/eureka

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:

    metadata-map:
      management.port: ${server.port} # Port for management endpoints
      status-page-url-path: /actuator/info # Endpoint for health check
      health-check-url-path: /actuator/health # Endpoint for health check
      lease-renewal-interval-in-seconds: 10 # Eureka renewal interval
      lease-expiration-duration-in-seconds: 30 # Eureka expiration duration

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always # Show detailed health information
