version: '3.9'

services:
  service-config:
    container_name: s09-service-config
    #pull_policy: always -- why?
    image: application/config-server:naive
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      backend:
        aliases:
          - "service-config"

  service-discovery:
    container_name: service-discovery-spring
    #pull_policy: always -- why?
    image: application/discovery-service:naive
    ports:
      - "8761:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 20s
      retries: 5
      start_period: 9s
    environment:
      SERVER_PORT: 8080
    depends_on:
      - service-config
    networks:
      backend:
        aliases:
          - "service-discovery"

  examinator:
    container_name: examinator-container
    image: application/examinator:naive
    #pull_policy: always
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    environment:
      SERVER_PORT: 8080
      SPRING_CONFIG_IMPORT: "optional:configserver:http://service-config:8888"
    depends_on:
      service-config:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "examinator"

networks:
  backend:
    driver: bridge